M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-12-11T12:23:00+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-11T12:23:00+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X136.667Y-42.983
X162.067Y-42.983
M30
